### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by daniftinca** [kombai/freewall#202]
Please add a better documentation. I am trying to figure this thing out for 2 days already.

**Comment by drawcard** [comment]
What are you trying to figure out exactly? You can probably work it out by right clicking on one of the demo pages and taking a look at the source code.

**Comment by daniftinca** [comment]
my boss wants me to use this and i have no idea how. I got it working eventually but it is still buggy. 
The images load in a diffrent order on mozilla and chrome and the second of my 2 galleries loads with images of random widths and heights, over the next element. Than they go back on the slightest width or height change (including when i click on inspect element).

**Comment by drawcard** [comment]
Can you post a screenshot? Or share some code?

**Comment by daniftinca** [comment]
ok. right when i load the page the galleries are all crammed up and over the rest of the content like in screen1. After resize they all go back to their original position

Screen1: ![screen1](https://cloud.githubusercontent.com/assets/17156755/13251915/c99cf196-da3b-11e5-8447-04bb9555dcca.png)

Screen2: 
![screen2](https://cloud.githubusercontent.com/assets/17156755/13251926/da38c3fe-da3b-11e5-8080-d1e621ac8ebf.png)

**Comment by drawcard** [comment]
Looks like you might need to write some CSS rules to constrain the sizes of each panel, so Freewall has something to work with. I usually set a common width for all elements and leave the height variable.

**Comment by drawcard** [comment]
Actually ignore all that sh*t I just wrote.

I think the problem is that Freewall isn't being fired on page load, but it is whenever you resize the page.

Can you post the JS you're using to trigger Freewall, ie. the Jquery code?

**Comment by natyconnor** [comment]
I also think there definitely needs to be better documentation for this tool. It's powerful, but all the examples are with divs of set height, which isn't that useful of a case. I'm having an issue with getting the following:

![bad freewall](https://cloud.githubusercontent.com/assets/831626/13307252/cd939fd2-db1e-11e5-8dcf-2c9341556205.png)

Without freewall it's pretty much what I want:

![good wall](https://cloud.githubusercontent.com/assets/831626/13307256/dbdd9db8-db1e-11e5-90d5-704b273051d1.png)

But I'd love to use the filtering provided by freewall. I would think code like this would work:
```
requestWall.reset({
		selector: '.request-cell',
		animate: true,
		cellW: 'auto',
		cellH: '100',
		fixSize: false,
		onResize: function() {
			requestWall.fitWidth();
		}
```
but that height doesn't work and they're overlapping each other horizontally for some reason. I've tried setting heights and gutters and nothing ever really works. Some more practical, real world cases where the content isn't just a colored box would be really useful for using this otherwise awesome tool.

**Comment by daniftinca** [comment]
@drawcard here is the code i used for it:

$(document).ready(function() {
	$(function() {
			var wall = new freewall("#freewall");
			wall.reset({
			  selector: '.item ',
			  animate: true,
			  gutterY: 0,
			  gutterX: 0,
				onResize: function() {
						wall.fitWidth();                       
					}
			});
			wall.fitZone();
	});
     $(function() {
			var wall = new freewall("#freewall2");            
			wall.reset({
			  selector: '.item2 ',
			  animate: true,
			  gutterY: 0,
			  gutterX: 0,                 
				onResize: function() {
						wall.fitWidth();                    
					}
			});
			wall.fitZone();
	});

**Comment by jaimz22** [comment]
@drawcard suggesting someone look at the examples is kind of crap to be honest. it wouldn't hurt to have a simple list of all the options and how to actually use the library.

**Comment by drawcard** [comment]
@jaimz22 what exactly do you mean? That's how I learnt to use Freewall. It's not the best method of course but when the docs don't explain anything better, it's all you have to go on.
